version: '3'

services:
  varnish:
    build: 
      context: "./varnish"
      args:
        - cachesize=1G
    ports:
      - 8088:80
    networks: 
      - local
  exist:
    build: .
    ports:
      - 8080:8080
    networks: 
      - local
networks:
  local:    

