version: '3.6'

services:
  varnish:
    build: 
      context: "./varnish"
      args:
        - cachesize=1G
    ports:
      - 8088:80
    networks: 
      - local
  existdb:
    build: .
    ports:
      - 8080:8080
    networks: 
      - local
    restart: unless-stopped
networks:
  local: 
     

